### ISSUE TITLE
Cannot delete any item from shopping cart

### ISSUE THREAD

**Issue by clarrat** [printdotio/printio-ios-sdk#530] opened 2017-08-22 13:33 UTC
Hi, i tried out your sdk for IOS. Everyting works except for deleting some item from the shopping cart. Is this a bug?

**Comment by ivankovicmilos** [comment] 2017-08-22 14:44
Hello, 

Can you provide steps of issue or to record video? 

How do you try to delete item in cart? with swiping or with remove button?

Thanks

**Comment by clarrat** [comment] 2017-08-23 10:58
Hi @ivankovicmilos ,

with the remove button. I think a popup should appear when I click on the delete button. But nothing is shown. There is also no output in the console. 

[http://de.tinypic.com/r/x27amu/9](url)

Thanks

**Comment by clarrat** [comment] 2017-08-25 14:39
Hi @ivankovicmilos ,

i could identify the error. if i set the following Firebase dependency in my PODFILE, the overlays don't show up in the Gotten module:

> pod 'Firebase/AdMob'

Do you know why?

**Comment by ivankovicmilos** [comment] 2017-08-25 15:08
@clarrat Hi, this is question for our dev
@perisicboro, please help here.

So far, i was unable to reproduce this issue on our end. Delete button works good on real device and on simulator so if you can, please share exact steps with screenshots or record video of whole process. Also, can you tell me which version of SDK, iOS and model of phone you are using

thanks

**Comment by clarrat** [comment] 2017-08-28 10:55
I have created a test project to reproduce the error. Please give me an email address to send you the download link.

thanks

**Comment by ivankovicmilos** [comment] 2017-08-28 12:00
@clarrat Did you reproduce this issue on real device or just on simulator?
as i asked, please share with us video of whole process. from creating product until issue with 'remove' button. 
Here is my email, i will try to recreate on my device
milosi@gooten.com

**Comment by perisicboro** [comment] 2017-08-30 09:58
@clarrat Fixed in v1.8.43(38)

**Closed by perisicboro** 2017-08-30 09:58 UTC
Labels: bug

**Comment by clarrat** [comment] 2017-09-05 19:21
The fix solved the problem. Thank you.
